spring.application.name=payandscan
server.address=0.0.0.0
server.port=8080

# local url
local.qr.url=http://192.168.29.104:8080/api/payments/scan-success/

# mongo db config
spring.mongodb.uri=mongodb://localhost:27017/payandscan

# redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=flaskwebapplication@gmail.com
spring.mail.password=ckqpoydvjcamkzhs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true